on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: swap
        run: |
          sysctl vm.swapusage
          vm_stat
          ls -lh /private/var/vm/swapfile* 
